# Generated by Django 3.0.5 on 2020-04-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200419_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='summary',
            field=models.TextField(default='This cool!'),
        ),
    ]
